disabled_rules:
  - custom_rules
  - discarded_notification_center_observer
  - trailing_newline
  - trailing_whitespace
  - type_body_length
  - empty_enum_arguments
  - file_length
  - function_body_length
  - is_disjoint
  - line_length
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - todo
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
#- explicit_type_interface
  - fatal_error_message
  - implicit_return
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
#- unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - private_action
  - private_outlet
excluded:
  - Pods

block_based_kvo:
  severity: warning
class_delegate_protocol:
  severity: error
closing_brace:
  severity: error
closure_parameter_position:
  severity: error
colon:
  severity: error
comma:
  severity: error
compiler_protocol_init:
  severity: error
control_statement:
  severity: error
discouraged_direct_init:
  severity: error
dynamic_inline:
  severity: error
empty_parameters:
  severity: error
fallthrough:
  severity: error
generic_type_name:
  severity: error
identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 60
    error: 60
implicit_getter:
  severity: error
large_tuple:
  error: 4
  warning: 4
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_nsgeometry_functions:
  severity: error
nesting:
  type_level:
    warning: 6
    error: 6
  statement_level:
    warning: 10
    error: 10
discouraged_optional_boolean:
  severity: error
opening_brace:
  severity: error
operator_whitespace:
  severity: error
private_over_fileprivate:
  severity: error
private_unit_test:
  severity: error
protocol_property_accessors_order:
  severity: error
redundant_discardable_let:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
shorthand_operators:
  severity: error
statement_position:
  severity: error
superfluous_disable_command:
  severity: error
switch_case_alignment:
  severity: error
syntactic_sugar:
  severity: error
trailing_comma:
  severity: error
trailing_semicolon:
  severity: error
type_name:
  min_length: 0
  max_length:
    warning: 60
    error: 60
unneeded_break_in_switch:
  severity: error
unused_closure_parameter:
  severity: error
unused_enumerated:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error
xctfail_message:
  severity: error
cyclomatic_complexity:
  error: 50
  warning: 40
empty_parentheses_with_trailing_closure:
  severity: error
for_where:
  severity: error
force_cast:
  severity: error
force_try:
  severity: error
function_parameter_count:
  error: 5
  warning: 5
mark:
  severity: error
redundant_string_enum_value:
  severity: error
unused_optional_binding:
  severity: error
array_init:
  severity: error
closure_end_indentation:
  severity: error
closure_spacing:
  severity: error
contains_over_first_not_nil:
  severity: error
#explicit_type_interface:
#  severity: error
#  excluded:
#    - local
fatal_error_message:
  severity: error
implicit_return:
  severity: error
implicitly_unwrapped_optional:
  severity: error
literal_expression_end_indentation:
  severity: error
multiline_parameters:
  severity: error
operator_usage_whitespace:
  severity: error
overridden_super_call:
  severity: error
override_in_extension:
  severity: error
pattern_matching_keywords:
  severity: error
prohibited_super_call:
  severity: error
redundant_nil_coalescing:
  severity: error
single_test_class:
  severity: error
sorted_first_last:
  severity: error
#unneeded_parentheses_in_closure_argument:
#  severity: error
vertical_parameter_alignment_on_call:
  severity: error
yoda_condition:
  severity: error
force_unwrapping:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error

reporter: "xcode"
